/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Collections;
import java.util.Comparator;
import java.util.Arrays;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Deviay
 */
public class FormGUI extends javax.swing.JFrame {

    /**
     * Creates new form FormGUI
     */
    Tes test = new Tes();
    public FormGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(java.awt.Color.gray);

        jButton1.setText("Staff");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Faculty");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Part Time");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("TOTAL");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("TOTAL");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("KELOMPOK 5 ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("PAYROLL SYSTEM");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel3.setText("MENU");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel4.setText("Total Monthly Salary For Part Time Staff");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setText("Total Monthly Salary For Part All Employees");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel7.setText("Winda Sofia (20051214100)");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel8.setText("Nimas Ayuningtyas (20051214056)");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel9.setText("Deviananda Yunitasari (20051214070)");

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel10.setText("Maraqonitatilla (20051214064)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SimpleDateFormat format = new SimpleDateFormat("mm/dd/yy");
        Employee emp[] = new Employee[3];
        try {
            emp[0] = new Staff("Allen","Paita","123",'M',format.parse("2/23/59"),50.00);
            emp[1] = new Staff("Zapatan","Steven","456",'F',format.parse("7/12/64"),35.00);
            emp[2] = new Staff("Rios","Enrique","789",'M',format.parse("6/2/70"),40.00);
        } catch (ParseException ex) {
            Logger.getLogger(FormGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (Employee emp1 : emp) {
            JOptionPane.showMessageDialog(null, emp1 + "");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SimpleDateFormat format = new SimpleDateFormat("mm/dd/yy");
        Employee emp[] = new Employee[3];
        try {
            emp[0] = new Faculty("Johnson","Anne","234",'F',format.parse("4/27/62"),Faculty.Level.FU,new Education("Ph.D","Engineering",3));
            emp[1] = new Faculty("Bouris","William","791",'F',format.parse("3/14/75"),Faculty.Level.AO,new Education("Ph.D","English",1));
            emp[2] = new Faculty("Andrade","Christopher","623",'F',format.parse("5/22/80"),Faculty.Level.AS,new Education("MS","Physical Education",0));
        } catch (ParseException ex) {
            Logger.getLogger(FormGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (Employee emp1 : emp) {
            JOptionPane.showMessageDialog(null, emp1 + "");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        SimpleDateFormat format = new SimpleDateFormat("mm/dd/yy");
        Employee[] employee = new Employee[9];
        
        try {
            employee[0] = new Staff("Allen","Paita","123",'M',format.parse("2/23/59"),50.00);
            employee[1] = new Staff("Zapatan","Steven","456",'F',format.parse("7/12/64"),35.00);
            employee[2] = new Staff("Rios","Enrique","789",'M',format.parse("6/2/70"),40.00);
            employee[3] = new Faculty("Johnson","Anne","234",'F',format.parse("4/27/62"),Faculty.Level.FU,new Education("Ph.D","Engineering",3));
            employee[4] = new Faculty("Bouris","William","791",'F',format.parse("3/14/75"),Faculty.Level.AO,new Education("Ph.D","English",1));
            employee[5] = new Faculty("Andrade","Christopher","623",'F',format.parse("5/22/80"),Faculty.Level.AS,new Education("MS","Physical Education",0));
            employee[6] = new Partime("Augusto","Guzman","455",'F',format.parse("8/10/77"),35.00,30);
            employee[7] = new Partime("Martin","Depirro","678",'F',format.parse("9/15/87"),30.00,15);
            employee[8] = new Partime("Marque","Aldaco","945",'M',format.parse("11/24/88"),20.00,35);
        } catch (ParseException ex) {
            Logger.getLogger(FormGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        double total_salary = 0.0;
        for (Employee emp : employee) {
            if (emp.getClass() == Staff.class) {
             /* checking if its a Staff object */
                total_salary += emp.monthlyEarning();
            }
        }
        JOptionPane.showMessageDialog(null, "Total Monthly Salary for All Employees : " + "$" + total_salary + "\n");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        SimpleDateFormat format = new SimpleDateFormat("mm/dd/yy");
        Employee[] employee = new Employee[9];
        try {
            employee[0] = new Staff("Allen","Paita","123",'M',format.parse("2/23/59"),50.00);
            employee[1] = new Staff("Zapatan","Steven","456",'F',format.parse("7/12/64"),35.00);
            employee[2] = new Staff("Rios","Enrique","789",'M',format.parse("6/2/70"),40.00);
            employee[3] = new Faculty("Johnson","Anne","234",'F',format.parse("4/27/62"),Faculty.Level.FU,new Education("Ph.D","Engineering",3));
            employee[4] = new Faculty("Bouris","William","791",'F',format.parse("3/14/75"),Faculty.Level.AO,new Education("Ph.D","English",1));
            employee[5] = new Faculty("Andrade","Christopher","623",'F',format.parse("5/22/80"),Faculty.Level.AS,new Education("MS","Physical Education",0));
            employee[6] = new Partime("Augusto","Guzman","455",'F',format.parse("8/10/77"),35.00,30);
            employee[7] = new Partime("Martin","Depirro","678",'F',format.parse("9/15/87"),30.00,15);
            employee[8] = new Partime("Marque","Aldaco","945",'M',format.parse("11/24/88"),20.00,35);
        } catch (ParseException ex) {
            Logger.getLogger(FormGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        double total_part_time = 0.0;

        for (Employee emp1 : employee) {
            if (emp1 instanceof Partime) {
                total_part_time += emp1.monthlyEarning();
            }
        }
        JOptionPane.showMessageDialog(null, "Total Monthly Salary for Part Time Staff : " + "$" + total_part_time + "\n");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        SimpleDateFormat format = new SimpleDateFormat("mm/dd/yy");
        Employee emp[] = new Employee[3];
        try {
            emp[0] = new Partime("Augusto","Guzman","455",'F',format.parse("8/10/77"),35.00,30);
            emp[1] = new Partime("Martin","Depirro","678",'F',format.parse("9/15/87"),30.00,15);
            emp[2] = new Partime("Marque","Aldaco","945",'M',format.parse("11/24/88"),20.00,35);
        } catch (ParseException ex) {
            Logger.getLogger(FormGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (Employee emp1 : emp) {
            JOptionPane.showMessageDialog(null, emp1 + "");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
